name: wxr-messenger lambda deploy workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: wxr-messenger
        run: npm install
      - name: Build
        working-directory: wxr-messenger
        run: npm run dist
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to Lambda
        working-directory: wxr-messenger
        run: |
          aws lambda update-function-code \
            --function-name wxr-messenger-auto-responder-email-handler \
            --zip-file fileb://dist/lambda.zip && \
          aws lambda update-function-code \
            --function-name wxr-messenger-auto-responder-event-handler \
            --zip-file fileb://dist/lambda.zip
